[theme]
base = "dark"
primaryColor = "#00A19C"
backgroundColor = "#090A0B"
secondaryBackgroundColor = "#111315"
textColor = "#F4F7F8"
font = "sans serif"
[server]
headless = true
runOnSave = false
[browser]
gatherUsageStats = false
